version: "3.8"

services:
  rule-engine:
    container_name: promotion-rule-engine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - RULE_FILE=/app/rules.yaml
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
